Json patch
StackStorm-Exchange/stackstorm-icinga2 pull request #14
Opened 2020-10-05 18:32 UTC by thozook

Adjusted so that the JSON load is a bit more tolerant of invalid JSON.

- Added a function to escape all backslashes in the JSON object before it is loaded
- Adjusted the JSON load with strict=false so that control characters are allowed in the strings

2020-10-05 19:55 UTC, nmaludy requested changes
@thozook Thank you very much for this fix. Would you please do the following additional steps and we can get this merged?

- Add an entry to CHANGELOG.md
- Bump the version in `pack.yaml` by 0.0.1 to indicate a bug fix

Thank you again!

2020-10-05 21:31 UTC, thozook commented
> @thozook Thank you very much for this fix. Would you please do the following additional steps and we can get this merged?
> 
> * Add an entry to CHANGES.md
> * Bump the version in `pack.yaml` by 0.0.1 to indicate a bug fix
> 
> Thank you again!

Version in pack.yaml bumped and entry in CHANGES.md created.

2020-10-06 11:57 UTC, nmaludy approved these changes

2020-10-06 11:59 UTC, merged

2020-10-06 11:59 UTC, nmaludy commented
@thozook Thank you very much for your contribution! Since this is your first time contributing to the project i would like to offer you some StackStorm stickers, if you're interested please email me your shipping address to nick@stackstorm.com

Thanks!